export const HOME = "/home";
export const LANDINGPAGE = "/landingpage";
export const USERPAGE = "/userpage";
export const DISPLAYPAGE = "/displaypage";
export const FAVORITEPAGE = "/favorites";
export const SEARCHPAGE = "/search";
export const ADDMUSICPAGE = "/addmusic";
export const MYSONGSPAGE = "/mysongs";
// export const MICHELE = "/michele"
export const GENRE = "/genre/:genreId";
export const PLAYLISTPAGE = "/playlist/:playlistName";
export const PLAYLISTALL = "/playlist/";
